### ISSUE TITLE
Shelter Style Refresh - Line Ver. Dark Theme

### ISSUE THREAD

**Issue by reitenth** [ValerioLyndon/Theme-Customiser-Json#5]
would it be possible to get a dark theme for this theme? thanks!

**Comment by ValerioLyndon** [comment]
Done, should be [live on the page now](https://valeriolyndon.github.io/Theme-Customiser/theme?t=https://valeriolyndon.github.io/Theme-Customiser-Json/Takana no Hana/Shelter Style Refresh Line.json).

Does not currently change the images as it always makes the code a bit messy to prevent conflicts with user image choices.

![](https://i.imgur.com/FkzlJhL.jpeg)
